//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to choose components.
        /// </summary>
        public static string aboutBtn {
            get {
                return ResourceManager.GetString("aboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To cart.
        /// </summary>
        public static string InCart {
            get {
                return ResourceManager.GetString("InCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear choice.
        /// </summary>
        public static string IndChPageClearToolBarItem {
            get {
                return ResourceManager.GetString("IndChPageClearToolBarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent choice.
        /// </summary>
        public static string IndepPageTitle {
            get {
                return ResourceManager.GetString("IndepPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do we start?.
        /// </summary>
        public static string IndPageLabel {
            get {
                return ResourceManager.GetString("IndPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —  from the case.
        /// </summary>
        public static string IndPageListItemCase {
            get {
                return ResourceManager.GetString("IndPageListItemCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — from the processor.
        /// </summary>
        public static string IndPageListItemCPU {
            get {
                return ResourceManager.GetString("IndPageListItemCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —  from the video card.
        /// </summary>
        public static string IndPageListItemGPU {
            get {
                return ResourceManager.GetString("IndPageListItemGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —  from the motherboard.
        /// </summary>
        public static string IndPageListItemHDD {
            get {
                return ResourceManager.GetString("IndPageListItemHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —  from the hard drive.
        /// </summary>
        public static string IndPageListItemMotherboard {
            get {
                return ResourceManager.GetString("IndPageListItemMotherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —  from the power supply.
        /// </summary>
        public static string IndPageListItemPowerSupply {
            get {
                return ResourceManager.GetString("IndPageListItemPowerSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —  from RAM.
        /// </summary>
        public static string IndPageListItemRAM {
            get {
                return ResourceManager.GetString("IndPageListItemRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case selection.
        /// </summary>
        public static string ItemsPageCaseTitle {
            get {
                return ResourceManager.GetString("ItemsPageCaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU selection.
        /// </summary>
        public static string ItemsPageCPUTitle {
            get {
                return ResourceManager.GetString("ItemsPageCPUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video card selection.
        /// </summary>
        public static string ItemsPageGPUTitle {
            get {
                return ResourceManager.GetString("ItemsPageGPUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard drive selection.
        /// </summary>
        public static string ItemsPageHDDTitle {
            get {
                return ResourceManager.GetString("ItemsPageHDDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no corresponding subjects.
        /// </summary>
        public static string ItemsPageLabel {
            get {
                return ResourceManager.GetString("ItemsPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ItemsPageMenuItemSelect {
            get {
                return ResourceManager.GetString("ItemsPageMenuItemSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motherboard selection.
        /// </summary>
        public static string ItemsPageMotherboardTitle {
            get {
                return ResourceManager.GetString("ItemsPageMotherboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Supply Selection.
        /// </summary>
        public static string ItemsPagePowerSupplyTitle {
            get {
                return ResourceManager.GetString("ItemsPagePowerSupplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM selection.
        /// </summary>
        public static string ItemsPageRAMTitle {
            get {
                return ResourceManager.GetString("ItemsPageRAMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the program.
        /// </summary>
        public static string mainPageTitle {
            get {
                return ResourceManager.GetString("mainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string MasterPageItemAboutTitle {
            get {
                return ResourceManager.GetString("MasterPageItemAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MasterPageItemMainTitle {
            get {
                return ResourceManager.GetString("MasterPageItemMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MasterPageItemSettingsTitle {
            get {
                return ResourceManager.GetString("MasterPageItemSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready assemblies.
        /// </summary>
        public static string readyBtn {
            get {
                return ResourceManager.GetString("readyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catalog search.
        /// </summary>
        public static string searchEntry {
            get {
                return ResourceManager.GetString("searchEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the settings to take effect, you must restart the application.
        /// </summary>
        public static string SettingsPageDisplayAlertText {
            get {
                return ResourceManager.GetString("SettingsPageDisplayAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string SettingsPageDisplayAlertTitle {
            get {
                return ResourceManager.GetString("SettingsPageDisplayAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language.
        /// </summary>
        public static string SettingsPageLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPageLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsPagePickerTitle {
            get {
                return ResourceManager.GetString("SettingsPagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional settings.
        /// </summary>
        public static string SettingsPageTableSelectionLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTableSelectionLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t chosen anything yet.
        /// </summary>
        public static string ShoppingCartPageEmptyLabel {
            get {
                return ResourceManager.GetString("ShoppingCartPageEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent choice.
        /// </summary>
        public static string singleBtn {
            get {
                return ResourceManager.GetString("singleBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program name.
        /// </summary>
        public static string StartPageTitle {
            get {
                return ResourceManager.GetString("StartPageTitle", resourceCulture);
            }
        }
    }
}
